on:
  schedule:
    - cron: '59 10 1 * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://ci-cd-fullstack-ex-11-22-2021.herokuapp.com/health
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1